#!/bin/bash
# Get External IP / Internet Speed
alias myip="curl https://ipinfo.io/json" # or /ip for plain-text ip
alias speedtest="curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py | python -"

alias serve='ruby -run -e httpd . -p 8000'  # Or python -m SimpleHTTPServer :)

alias kitt="open https://kitt.lewagon.com/"

# Open tickets page
tickets() {
  open https://kitt.lewagon.com/camps/$1/tickets
}

camp() {
  open https://kitt.lewagon.com/camps/$1
}

# Open calendar page
calendar() {
  open https://kitt.lewagon.com/camps/$1/calendar
}

# Open classmates page
classmates() {
  open https://kitt.lewagon.com/camps/$1/classmates
}

# Open dashboard page
dashboard() {
  open https://kitt.lewagon.com/camps/$1/day_dashboard
}

# Open statistics page
stats() {
  open https://kitt.lewagon.com/camps/$1/tickets/day_dashboard
}

# search alumni on kitt
kittsearch() {
  open https://kitt.lewagon.com/alumni\?search=$1
}

# alumni show
alumni() {
  open https://kitt.lewagon.com/alumni/$1
}

# feedbacks index
feedbacks() {
  open https://kitt.lewagon.com/camps/$1/feedbacks
}

# products
products() {
  open https://kitt.lewagon.com/camps/$1/products
}

# Open webpage
web() {
  open https://www.$1
}

# Open slack
alias slack="open -a 'slack'"

# Open an app
app() {
  open -a "$1"
}

# Open repo
repo() {
  if [ $# -eq 1 ];
    then
      open https://www.github.com/$1
  elif [ $# -eq 2 ];
    then
      open https://www.github.com/$1/$2
  else
    echo "Usage: repo [user] [repo]"
  fi
}

# Open repo in cs.github.com
cs() {
  if [ $# -eq 1 ];
    then
      open https://cs.github.com/$1
  elif [ $# -eq 2 ];
    then
      open https://cs.github.com/$1/$2
  else
    echo "Usage: repo [user] [repo]"
  fi
}

# Open PRs of repo
pr() {
  if [ $# -eq 2 ];
    then
      open https://www.github.com/$1/$2/pulls
  elif [ $# -eq 3 ];
    then
      open https://www.github.com/$1/$2/pull/$3
  else
    echo "Usage: pr <owner> <repo> [<pr_number>]"
  fi
}

# Open issues of repo
issues() {
  open https://www.github.com/$1/$2/issues
}

# navigate in code folder
goto() {
  cd ~/src/$1
}

# navigate in folder and open
sttt() {
  cd ~/src/$1; stt;
}

# start mongodb
alias mongodb='$HOME/mongodb/bin/mongod --dbpath=$HOME/mongodb-data'

# launch webpack-dev-server
alias wds='webpack-dev-server'

# used nvmrc version and launch webpack-dev-server
alias nwds='nvm use && webpack-dev-server'

# rails console
alias rc="bin/rails c"

# rails server
alias rs="bin/rails s"

# rails db:migrate
alias rdbm="bin/rails db:migrate"

# rails db:rollback
alias rdbr="bin/rails db:rollback"

# rails db:seed
alias rdbs="bin/rails db:seed"

# rails db:reset
alias rdbrst="rails db:reset"

# rails db:drop
alias rdbd="bin/rails db:drop"

# rails db:create
alias rdbc="bin/rails db:create"

# rails db:drop db:create db:migrate db:seed
alias rdb="bin/rails db:drop db:create db:migrate db:seed"

# jupyter notebook
alias jn="jupyter notebook"

jslides() {
  # jupyter nbconvert --to slides --post serve $1
  ls *.ipynb | entr -r jupyter nbconvert "$1" --to slides --post serve --TemplateExporter.extra_template_basedirs=../templates --template=kitt;
}

# Delete squashed and merged branches
alias sweep='git checkout -q main && git for-each-ref refs/heads/ "--format=%(refname:short)" | while read branch; do mergeBase=$(git merge-base main $branch) && [[ $(git cherry main $(git commit-tree $(git rev-parse $branch^{tree}) -p $mergeBase -m _)) == "-"* ]] && git branch -D $branch; done'

# kill server
killserver() {
  kill -9 $(lsof -ti:$1)
}
